# Generated by Django 3.1.4 on 2021-01-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('startingBid', models.DecimalField(decimal_places=2, max_digits=99)),
                ('imageURL', models.URLField(max_length=999)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
