# Generated by Django 3.1.4 on 2021-01-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, max_length=99999),
        ),
    ]
