# Generated by Django 3.1.4 on 2021-01-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_maxbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='openListing',
            field=models.BooleanField(default=True),
        ),
    ]
