# Generated by Django 3.1.4 on 2021-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-6.png', max_length=99999),
        ),
    ]
