# Generated by Django 3.1.4 on 2021-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210108_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentDuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
